In [1]:
import numpy as np

Question 1:

In [24]:
f = np.array([
    [11,22,33],
    [44,55,66],
    [77,88,99]
])

print("First column:",f[:,0])
print("Last row:",f[2,:])
print(f[0:2,1:3])

First column: [11 44 77]
Last row: [77 88 99]
[[22 33]
 [55 66]]


Question 2:

In [26]:
u = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print("First row:", u[0,:])
print("Second column:",u[:,1])
print(u[1,1])

First row: [10 20 30]
Second column: [20 50 80]
50


Question 3:

In [27]:
n = np.arange(1,13)
print("(3,4) Array:\n", n.reshape(3,4))
print("(2,6) Array:\n", n.reshape(2,6))
print("(2,3,2) Array:\n", n.reshape(2,3,2))

(3,4) Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(2,6) Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2,3,2) Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Question 4:

In [28]:
z = np.array([1,2,3])
x = np.array([4,5,6])

print("Addition of both arrays:",z+x)
print("Subtraction of both arrays:",z-x)
print("Multiplication of both arrays:",z*x)
print("Division of both arrays:",z/x)
print("Power of 3 of z:",z**3)
print("Power of 3 of x:",x**3)
print("Square of z:",z**2)
print("Square of x:",x**2)
print("mean of z:",np.mean(z))
print("mean of x:",np.mean(x))

Addition of both arrays: [5 7 9]
Subtraction of both arrays: [-3 -3 -3]
Multiplication of both arrays: [ 4 10 18]
Division of both arrays: [0.25 0.4  0.5 ]
Power of 3 of z: [ 1  8 27]
Power of 3 of x: [ 64 125 216]
Square of z: [1 4 9]
Square of x: [16 25 36]
mean of z: 2.0
mean of x: 5.0


Question 5:

In [29]:
o = np.random.randint(1,11, size=10)
print("Random array:", o)

p = np.random.randint(1,10,size=(3,3))
print("Random 3x3 array:\n", p)

Random array: [10 10  4  5 10  7  5  6  7  6]
Random 3x3 array:
 [[8 6 1]
 [5 6 6]
 [3 1 8]]


Question 6:

In [30]:
k = np.random.randint(1,100,size=(2,5))
print("Random 2x5 array:\n", k)

Random 2x5 array:
 [[84 82 51 83 14]
 [63 31 81 76  6]]


Question 7:

In [31]:
# in python list any type of data can be stored and it is allocated in that order of the datatype but in numpy arrays only one type of data can be stored and it results in faster matrix operations

Question 8:

In [32]:
a = np.array([1,2,3,4])
print("original type:",a.dtype)

a_f= a.astype(float)

print(a_f)
print("\nnew type:",a_f.dtype)

original type: int64
[1. 2. 3. 4.]

new type: float64


Question 9:

In [33]:
""" dtype is only used to check the datatype of the array and reads the datatype only but
    astype() is used to change the datatype of the array and it creates a new array with the new datatypw """

' dtype is only used to check the datatype of the array and reads the datatype only but\n    astype() is used to change the datatype of the array and it creates a new array with the new datatypw '

Question 10:

In [34]:
mat = np.random.randint(1,100,size=(3,3))

print("Original matrix:\n", mat)

print("\nShape(rows,columns):", mat.shape)
print("Number of elements:", mat.size)
print("Number of axes:", mat.ndim)
print("Datatype:", mat.dtype)

mat_f = mat.astype(float)
print("\nNew datatype:", mat_f.dtype)
print("New matrix:\n", mat_f)

Original matrix:
 [[53 59 53]
 [20 81 85]
 [35 70 85]]

Shape(rows,columns): (3, 3)
Number of elements: 9
Number of axes: 2
Datatype: int32

New datatype: float64
New matrix:
 [[53. 59. 53.]
 [20. 81. 85.]
 [35. 70. 85.]]


Question 11:

In [37]:
j  = np.array([1,2,3,4])
print(j[:,1])

# since we use a comma in [:,1], it is forced to look for a second dimension even though it does not exist, so it gives error for too many indices, it should be like [1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed